import streamlit as st
import sqlite3
import pandas as pd
import random
from datetime import datetime, timedelta
import faker
import json
import io
import zipfile

# Initialize Faker for random data generation
fake = faker.Faker()

# Connect to SQLite database (backup simulation)
conn = sqlite3.connect("utilities.db", check_same_thread=False)
c = conn.cursor()

# --- Create tables if not exist ---
c.execute("""
CREATE TABLE IF NOT EXISTS customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  email TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zip TEXT
);
""")

c.execute("""
CREATE TABLE IF NOT EXISTS utility_accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_id INT,
  provider TEXT,
  service_type TEXT,
  account_number TEXT,
  FOREIGN KEY(customer_id) REFERENCES customers(id)
);
""")

c.execute("""
CREATE TABLE IF NOT EXISTS bills (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  account_id INT,
  billing_period DATE,
  amount_due DECIMAL,
  due_date DATE,
  status TEXT,
  provider_invoice TEXT,
  FOREIGN KEY(account_id) REFERENCES utility_accounts(id)
);
""")

c.execute("""
CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bill_id INT,
  amount DECIMAL,
  payment_date TIMESTAMP,
  method TEXT,
  status TEXT,
  FOREIGN KEY(bill_id) REFERENCES bills(id)
);
""")

c.execute("""
CREATE TABLE IF NOT EXISTS directory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  city TEXT,
  provider TEXT
);
""")

# Seed directory for Harrisonburg if empty
c.execute("SELECT COUNT(*) FROM directory WHERE city = 'Harrisonburg'")
if c.fetchone()[0] == 0:
    providers = [
        "Access Gas Services",
"ACS Billing Service",
"AEP Energy",
"AEP Ohio",
"AEP Texas",
"AES Indiana",
"AES Ohio",
"Aigues de Barcelona",
"Alabama Power Company",
"Alameda County Water District",
"Alameda Municipal Power",
"Albany Utility",
"Albemarle County Service Authority",
"Albireo",
"Albuquerque Bernalillo County",
"Alderwood Water District",
"Alectra Utilities",
"Alexandria Renew Enterprises",
"All Waste Inc",
"Alliant Energy",
"Ameren Illinois",
"Ameren Missouri",
"American Water",
"AmeriGas",
"AmeriGas Propane",
"AmeriPower",
"Amherst",
"Anaheim Public Utilities Electric & Water",
"Anchorage Water & Wastewater Utility",
"Anderson City Utilities",
"Ann Arbor Daily",
"Anne Arundel County",
"AP Gas & Electric",
"Appalachian Power",
"Aqua America",
"Aqua Texas",
"Aquahawk",
"Aquarion MyCheckFree",
"Aquarion Water Company",
"Arapahoe County Water and Wastewater Authority , Colorado",
"Arizona Public Service",
"Arizona Water Company",
"Arlington VA",
"Arlington Water",
"Athens Services",
"Atlantic City Electric",
"Atmos Energy",
"Audax Energia",
"Augusta Utilities Department",
"AUM",
"Austin Energy",
"Austin Water",
"Aviator",
"AVID",
"Avid Bill Pay",
"Avista Corporation",
"Baldwin EMC",
"Baltimore Gas & Electric",
"Bangor",
"Bangor Gas",
"Bangor Hydro Electric",
"Bargersville",
"Bartow County Water Department",
"Bath Water",
"Battle Creek",
"BC Hydro and Water Authority",
"Beaufort Jasper",
"Beauregard",
"Belfast Water District",
"Berkeley Electric Cooperative",
"Berkshire Gas",
"Berlin",
"Bethalto Water Department",
"BG&E Landlord",
"Birmingham Water Works",
"Black Hills Energy",
"Bluebonnet Electric Cooperative",
"Bonita Springs Utilities",
"Boone REMC",
"Bord Gáis Energy",
"Borough of West Chester",
"Boston Water & Sewer",
"Boston Water Daily",
"Bowling Green Municipal Utilities",
"BP Energy Company",
"Brainerd Public Utilities",
"Braintree Electric Light",
"Brazoria County Municipal Utility District",
"Bristol Tennessee Essential Services",
"Bristol Water",
"Brockton",
"Brook Green Supply",
"Broward County Public Works",
"Buffalo Water",
"Burlington Electric - Energy Engage",
"Burlington Electric Department",
"Burlington Hydro Inc.",
"Burlington Water",
"C.F.A.T",
"California Water Services",
"Calpine Energy Solutions",
"Cambridge Water & Sewer",
"Canal de Isabel II",
"Canton Township Water Department",
"Capital Region Water",
"Capturis",
"Carpinteria Valley",
"Cascade Natural Gas",
"Cass",
"Cedar River Water & Sewer District",
"CenterPoint Energy",
"Central Arkansas Water",
"Central Georgia EMC",
"Central Hudson",
"Central Maine Power",
"Central Texas Refuse",
"Central Wisconsin Electric Cooperative",
"CenTrio",
"Champagne Energy Propane",
"Champion Energy Services",
"Charleston Water System",
"Charlotte and Mecklenburg County",
"Charlotte County",
"Charter Township of Grand Blanc",
"Charter Township of Washington",
"Cherokee Electric Coop",
"Chesapeake Utilities Corporation",
"Chugach Electric",
"Cinco M.U.D. #3",
"Cirro Energy",
"Citizens Energy",
"Citrus County Utilities",
"City of Abbotsford",
"City of Albany",
"City of Alcoa",
"City of Algona",
"City of Altoona",
"City of Americus",
"City of Anderson",
"City of Ankeny",
"City of Annapolis",
"City of Apopka",
"City of Arlington",
"City of Arlington, WA",
"City of Atlanta",
"City of Atlantic Beach",
"City of Auburn",
"City of Aurora",
"City of Austin",
"City of Avon",
"City of Avondale",
"City of Baltimore",
"City of Barrie",
"City of Beaverton",
"City of Bedford",
"City of Bellevue",
"City of Bellingham",
"City of Bentonville",
"City of Bern",
"City of Beverly Hills",
"City of Bloomington",
"City of Bluffton",
"City of Boca Raton",
"City of Boulder",
"City of Bradenton",
"City of Branson",
"City of Brantford, Ontario",
"City of Brea",
"City of Bromfield",
"City of Brookline",
"City of Buford, Georgia",
"City of Burbank",
"City of Burlingame",
"City of Burnaby",
"City of Burnsville",
"City of Calexico",
"City of Calgary, Canada",
"City of Camarillo",
"City of Carlsbad",
"City Of Carmel",
"City of Carrollton",
"City of Cedar Park",
"City of Cerritos",
"City of Chandler",
"City of Charlotte",
"City of Chelsea",
"City of Chicago",
"City of Chilliwack",
"City of Chino",
"City of Chino Hills",
"City of Clearwater",
"City of Coachella",
"City of Coconut Creek",
"City of Columbia",
"City of Columbus",
"City of Compton",
"City of Concord",
"City of Coppell",
"City of Corvallis",
"City of Covina",
"City of Daly City",
"City Of Dania Beach",
"City of Deerfield Beach",
"City of Dekalb",
"City of Delano",
"City of Delta",
"City of Denton",
"City of Dover",
"City of Downey",
"City of Dunedin",
"City of Durham",
"City of Eagan",
"City of Ecorse",
"City of El Segundo",
"City of Elgin",
"City of Ellensburg",
"City of Escalon",
"City of Everett",
"City of Fairfield",
"City of Fayetteville",
"City of Fillmore",
"City of Firebaugh",
"City of Flagstaff",
"City of Fort Lauderdale",
"City of Fort Pierce",
"City of Foster City",
"City of Franklin",
"City of Fremont",
"City of Frisco",
"City of Fullerton",
"City of Gainesville",
"City of Galion",
"City of Georgetown",
"City of Glendale",
"City of Glendora",
"City of Gonzales",
"City of Grand Rapids",
"City of Grapevine",
"City of Grass Valley",
"City of Greeley",
"City of Greenfield",
"City of Greensboro",
"City of Gresham",
"City of Gulfport",
"City of Hartford",
"City of Hayward",
"City of Healdsburg",
"City of Hermiston",
"City of Hollywood",
"City of Houston",
"City of Huber Heights",
"City of Huntington Beach",
"City of Irving",
"City of Kamloops",
"City Of Kent",
"City of Kilgore",
"City of Kirkland",
"City of Kyle",
"City of La Palma",
"City Of Lacey",
"City of Lake Mary",
"City of Lamar",
"City of Lancaster",
"City of Langley",
"City of Las Cruces",
"City of Lathrop",
"City of Lauderhill",
"City of Lawrence",
"City of Lebanon",
"City of Lebanon IN",
"City of Leesburg",
"City of Leominster",
"City of Lewisville",
"City of Loveland",
"City of Lynchburg",
"City of Madison",
"City of Manhattan Beach",
"City of Martinez",
"City of Marysville",
"City of Mebane",
"City of Menlo Park",
"City of Mercer Island",
"City of Meridian",
"City of Mesa",
"City of Middletown",
"City of Milford",
"City of Minden",
"City of Minneapolis",
"City of Minnetonka",
"City of Minot",
"City of Miramar",
"City of Missoula",
"City of Moncton",
"City of Montrose",
"City of Mount Dora",
"City of Mountain View",
"City of Nacogdoches",
"City of Nampa",
"City of Naperville",
"City of New Bedford",
"City of New Braunfels",
"City of New Smyrna Beach",
"City of Newburyport",
"City of Newport Beach",
"City of Norman",
"City of North Las Vegas",
"City of North Miami Beach",
"City of Oak Ridge",
"City of Oakdale CA",
"City of Ocala",
"City of Oceanside",
"City of Olympia",
"City of Orange",
"City of Ottawa",
"City of Oxnard",
"City of Palm Coast",
"City of Palo Alto",
"City of Pasadena",
"City of Patterson",
"City of Pembroke Pines",
"City of Peoria",
"City of Petaluma",
"City of Petoskey",
"City of Pflugerville, Texas",
"City of Phoenix",
"City of Plano",
"City of Plant City",
"City of Pleasanton",
"City of Plymouth",
"City of Pompano Beach",
"City of Pooler",
"City of Portsmouth",
"City of Poway",
"City of Prince George",
"City of Pullman",
"City of Raleigh",
"City of Redding",
"City of Redmond",
"City of Redwood",
"City of Regina CAN",
"City of Renton Water",
"City of Richardson",
"City of Richfield",
"City of Richmond",
"City of Ridgeland",
"City of Riverview",
"City of Rock Hill",
"City of Rollingwood TX",
"City of Roselle",
"City of Roseville",
"City of Round Rock",
"City of Sacramento Daily Water",
"City of Sacramento Dept of Utilities",
"City of San Luis Obispo",
"City of San Marcos",
"City of Santa Ana",
"City of Santa Barbara",
"City of Santa Clara",
"City of Santa Maria",
"City of Santa Monica",
"City of Schertz",
"City of Scottsdale",
"City of Seaford",
"City of Sevierville",
"City of Sheridan, Oregon",
"City of Southaven",
"City of St Albert",
"City of St. Louis Park",
"City of Statesville",
"City of Staunton",
"City of Sterling Heights, Michigan",
"City of Stillwater",
"City of Sugar Land",
"City of Sunnyvale",
"City of Sunrise",
"City of Surprise",
"City of Surrey",
"City of Tamarac",
"City of Tampa Utilities",
"City of Taunton",
"City of Tempe",
"City of Texas City",
"City of Tigard",
"City of Tomball",
"City of Toppenish",
"City of Toronto Water Division",
"City of Torrance",
"City of Tracy",
"City of Troy",
"City of Tualatin",
"City of Tulsa",
"City of Tustin",
"City of Vancouver",
"City of Ventura Water",
"City of Victoria",
"City of Virginia Beach",
"City of Waltham",
"City of Warren",
"City of Warwick",
"City of Wasco",
"City of Watauga",
"City of Watford",
"City of West Jordan",
"City of West Kelowna",
"City of West Linn",
"City of West Palm Beach",
"City of Westminster",
"City of Wildwood",
"City of Winnipeg Water and Waste Department",
"City Of Winston Salem",
"City of Wood River",
"City of Worcester",
"CityOfAustellGA::Water",
"Clackamas River",
"Clackamas Water Environment Services",
"Clark County Rural Electric Membership Corporation",
"Clark Electric Cooperative",
"Clark Public Utilities",
"Clarksville Department of Electricity",
"Clarksville Gas & Water",
"Clayton County Water Authority",
"Clean Sky Energy",
"Clearfield City",
"Cleco Power",
"Cleveland Division of Water",
"Cleveland Public Power",
"Cmpco Energy Manager",
"Coachella Valley Water District",
"Coahoma Electric Power Association",
"Coastside County Water",
"Cobb County",
"Cobb EMC",
"Collier County Utilities",
"Colorado Springs Utilities",
"Colton Public Utility",
"Columbia Gas",
"Columbia Gas of Ohio",
"ComEd",
"ComEd E-bill",
"Comisión Federal de Electricidad",
"Con Edison",
"Con Edison Orange and Rockland",
"Con Edison Retail",
"Con Edison Tcis",
"ConEd Corporate",
"ConEdison Retail",
"Connecticut Light & Power / Eversource",
"Connecticut Natural Gas",
"Connecticut Water",
"Connexus Energy",
"Conservice",
"Conservice Data Bridge",
"Conservice Detailed Utility Log",
"ConserviceDUL",
"Consolidated Utility District of Rutherford County",
"Consolidated Water District No. 1",
"Constellation Energy",
"Consumers Energy",
"Consumers Energy Bill Trust",
"Consumers Energy Landlord",
"Consumption Smart",
"Core Electric Cooperative",
"Corona",
"CoServ",
"County of Hawaii",
"County of Maui",
"CPS Energy",
"Cressman Sanitation",
"Cucamonga Valley Water District",
"Cumberland Electric Membership Corporation",
"Dallas Water",
"DC Water",
"Dead River Propane",
"Dedham-Westwood Water District",
"Dekalb County",
"Delmarva Power",
"Delta Twp",
"Denver Water",
"Des Moines Water Works",
"Detroit Water and Sewerage Dept",
"Direct Energy",
"Direct Energy Business",
"Direct Energy Business Portal",
"Dixie Electric Membership Corporation",
"DM Disposal",
"DMEA",
"Dominion East Ohio",
"Dominion Energy Property Manager",
"Dominion Energy Utah",
"Dominion Hope",
"Dominion North Carolina Power",
"Dominion South Carolina Power",
"Dominion Virginia Power",
"Douglassville-Douglas County Water & Sewer",
"Downers Grove Sanitary District",
"DTE Energy",
"DTE Landlord",
"Dubai Electricity & Water Authority",
"Dublin San Ramon Services District",
"Duke Energy",
"Duke Energy Large Business",
"Duke Energy Progress",
"Duke Energy Property Manager",
"Duquesne Light",
"Dyersburg Electric System",
"Dyersburg Gas & Water Department",
"East Central Energy",
"Eastern Municipal Water District",
"Easton",
"EBMUD",
"EDCO Disposal",
"EDP",
"Effingham County",
"El Dorado Water Utilities",
"El Paso Electric",
"El Paso Solar",
"El Paso Water Utilities Public Service Board",
"Electric Power Board",
"ElectriCities",
"Elexicon Energy",
"Elmhurst Power & Light",
"Emerald Coast Utilities Authority",
"Enbridge",
"Endesa SA",
"Enel Energia",
"Energia",
"Energie NB Power",
"Énergir",
"Energo",
"Energy Australia",
"Energy Cap",
"Energy Direct",
"Energy Plus Company",
"Energy United",
"Engie",
"Engie Impact",
"ENMAX Power Corporation",
"Enphase Energy",
"Enstar Gas",
"Entergy",
"Entergy Business Portal",
"Entrata",
"Enwave Seattle",
"Epcor Utilities",
"Ephrata",
"Epost Direct Energy",
"EpostEpcor",
"Equitable Gas",
"Erie Co. Department of Environmental Services",
"Erie County Water Authority",
"Escondido",
"Eugene Water & Electric Board",
"Everett Public Works",
"Evergy",
"Eversource",
"Fairfax Water",
"Fallbrook Public Utility District",
"First Utility District of Knox County",
"Flint Energies",
"Flogas",
"Florence",
"Florida Governmental Utility Authority",
"Florida Keys Aqueduct Authority",
"Florida Keys Electric Cooperative",
"Florida Power & Light",
"Flow Utility Management",
"FooFoo",
"Forsyth County",
"Fort Bend County Water Control & Improvement District",
"Fort Collins Utilities",
"Fort Wayne",
"Fort Worth",
"Fortis BC",
"Framingham Water",
"Fredericksburg",
"Fulton County Finance Department",
"Gainesville Regional Utilities",
"Gallatin Electric",
"Garden Grove",
"Garland",
"Gas South",
"GDF Suez",
"Georgetown Utilities",
"Georgia Natural Gas",
"Georgia Power",
"Georgia Power Landlords",
"Gesternova ESP",
"Gexa Energy",
"Glendale",
"GNHWPCA",
"Golden State Water",
"Goleta",
"Grand Prairie",
"Grand Strand Water & Sewer Authority",
"Greater Cincinnati Water Works",
"Greater Sudbury Hydro Incorporated",
"Green Mountain Energy",
"Green Mountain Power",
"Greenville Water",
"Greer CPW",
"Grey Forest Utilities",
"GreyStone Power Corporation",
"Groton Electric Light",
"Groton Utilities",
"Gulf Power",
"GulfPower",
"Gwinnett County Department of Water Resources",
"Hagerstown",
"Halifax Regional Water Commission",
"Hallsdale",
"Hardeman-Fayette Utility District",
"Harnett Regional Water",
"Harold Lemay Enterprises",
"Harris County MUD #383",
"Harris County Water",
"Harrison REMC",
"Hawaiian Electric Company",
"Hawaiian Electric Company Business",
"Hayward",
"Helix",
"Hendricks Power Cooperative",
"Henry County Water Authority",
"Hermiston Energy Services",
"Highline Water District",
"Hillsboro",
"Hingham Municipal Lighting Plant",
"Hobbs",
"HOCON Norwalk",
"HOCON Torrington",
"Holland Board of Public Works",
"Holland Charter Township",
"Holly Springs Utility Department",
"Holly Springs Water",
"Holyoke Gas & Electric",
"Holyoke No RegisteredAccount",
"Homefield Energy",
"Honolulu",
"Houston",
"Howard County",
"HRSD",
"Hudson Energy",
"Huntsville Utilities",
"Hurst",
"Hydro One",
"Hydro Ottawa",
"Hydro Quebec",
"Idaho Power",
"Imperial Irrigation District",
"Indiana Michigan Power",
"Indianapolis Power & Light",
"Infinite Energy",
"Inn Power",
"Integrys C&I",
"Interstate Gas Supply",
"Irish Water",
"IronHorse Power Services",
"Irvine Ranch Water District",
"J.S. West Propane",
"Jackson EMC",
"Jackson Energy Authority",
"Jacksonville",
"JEA",
"Jersey Central Power & Light",
"Jersey City Municipal Utilities Authority",
"Johnson City Utility System",
"Johnson County REMC",
"Johnson County Wastewater",
"Jurupa Community Services District",
"Kansas City Board of Public Utilities",
"Kansas City Water Services",
"Kansas Gas Service",
"Kearns Improvement District XpressBillPay",
"Kentucky Power",
"Kentucky Utilities Company",
"Keys Energy Service",
"King County Water",
"Kissimmee Utility Authority",
"Kitsap County Public Works",
"Knoxville Utilities Board",
"LA County",
"Laclede Gas",
"LADWP Summary Accounts",
"Lake Grove Water District",
"Lake Oswego",
"Lakehaven Utility District",
"Lakehurst Water and Sanitation District",
"Lakeview Light & Power",
"Lancaster County Water & Sewer District",
"Las Vegas Valley Water District",
"Las Virgenes Municipal Water District",
"Lassen Municipal Utility District",
"Lawrence",
"Lawrence Utilities",
"Lawrenceburg",
"Lebanon Utilities",
"Lee County Electric Coop",
"Lee County Utilities",
"Lehigh County Authority",
"Lenoir City Utilities Board",
"Liberty Utilities",
"Liberty Utilities Electric",
"Lincoln Energy Services",
"Lindsay",
"Linn County Rural Electric Cooperative",
"Littleton Water & Light",
"Long Beach",
"Los Angeles Dept. of Water & Power",
"Loudoun Water",
"Louisville Gas & Electric",
"Louisville Water",
"Lowell",
"Lumbee River EMC",
"Lynnwood",
"Macomb Township",
"Madison Gas & Electric",
"Magna Water Xpressbillpay",
"Malden Water",
"Mallory Valley Utility District",
"Manitoba Hydro Electric Energy & Natural Gas",
"Mansfield",
"Mansfield Municipal Electric Dept",
"Manteca",
"Marietta Power and Water",
"Marina",
"Mariposa PUD",
"Marquette Board of Light & Power",
"Martin County Utilities",
"MassCEC PTS",
"Maui Electric Company",
"Mayor & Council of Federalsburg",
"McKinney",
"McKinnleyville Community Services District Water",
"McMinnville",
"McPherson Public Utilities",
"Medford Water Commission",
"Medina County Sanitary Engineers",
"Memphis Light, Gas and Water",
"Menlo Park Municipal Water",
"Merced Irrigation District",
"Mesa Water District",
"Mesquite",
"Met-Ed",
"Metro Water",
"Metropolitan St. Louis Sewer District",
"Metropolitan Utilities District",
"MHOG Utilities",
"Miami Dade Water",
"Michigan Gas",
"Michigan Gas Utilities",
"Mid-Carolina Electric Cooperative",
"MidAmerican Energy",
"MidAmerican Energy Manager Assistant Portal",
"Middle Tennessee Electric",
"Midvalley Improvement District XpressBillPay",
"Milledgeville",
"Milwaukee Water Works",
"Minneapolis Water",
"Mishawaka Utilities",
"Mississippi Power",
"Missouri Gas Energy",
"Mobile Area Water and Sewer Systems",
"Mobile County",
"Mohave Electric Cooperative",
"Mon Power",
"Monroe",
"Monroe County Water Authority",
"Monrovia",
"Montana-Dakota Utilities Co.",
"Montgomery County",
"Montgomery Water Works and Sanitary Sewer Board",
"Mora Municipal Utilities",
"Morgan Hill",
"Moulton Niguel",
"Mount Pleasant Waterworks",
"Mount Vernon",
"Mount Werner Water District, Colorado",
"Mukilteo Water and Wastewater District",
"Municipal Utilities Commission",
"Murfreesboro Electric",
"Murray City",
"Narragansett Bay",
"Nashville Electric Service",
"National",
"National Fuel",
"National Grid",
"Nebraska Public Power District",
"New Jersey American Water",
"New Mexico Gas",
"New York State Electric and Gas",
"Newfoundland Power",
"NewHaven",
"Newmarket Hydro",
"Newnan Utilities",
"Newport News Waterworks",
"NH Electric Coop",
"Nicor Gas",
"NineStar Connect",
"North Huntingdon Township Municipal Authority",
"North Little Rock Electric",
"North Marin Water District",
"North Miami Beach",
"North Platte Light & Power",
"North Shore",
"Northeast Knox Utility District",
"Northern Indiana Public Service Co",
"Northern Virginia Electric Cooperative",
"Northshore Utility District",
"NorthWestern Energy",
"Norwich Public Utilities",
"Nova Scotia Power",
"Novak Sanitary Services",
"NRG Energy",
"NSTAR/ Eversource",
"NV Energy",
"NW Natural",
"NYC DEP Daily Water",
"NYC DEP Water",
"NYSEG for ESCOs",
"Oakville Hydro Electricity Distribution Inc.",
"OGE Electric",
"Ohio Edison",
"Oklahoma Electric Cooperative",
"Omaha Public Power District",
"Onondaga County Water",
"Ontario Municipal Utilities",
"Orange & Rockland",
"Orange County Utilities",
"Orlando Utilities",
"Orlando Utilities Commission",
"Orville Utilities",
"Oshawa PUC",
"Otay",
"Pacific Power",
"Padre Dam",
"Paduca Power System",
"Paducah Power System",
"Paducah Water System",
"Palm Beach County Water Utilities Department",
"Palmdale",
"Palmetto Electric Cooperative",
"Paris Board of Public Utilities",
"Parker Water & Sanitation District",
"Pasco County Utilities",
"Pascoag Utility District",
"Peace River Electric",
"PECO",
"Pedernales Electric Cooperative",
"Penelec",
"Penn Power",
"Pensacola Energy",
"Peoples E-account",
"Peoples Gas",
"Peoples Gas System",
"Peoples Natural Gas Co",
"Peoples Water Service Company",
"Pepco",
"Pepco Interval",
"PerformIQ",
"PG&E",
"PGE - CUSTOM FOR PGE",
"Philadelphia Gas Works",
"Pico Water District",
"Piedmont Natural Gas",
"Pine Hill Borough Municipal Utilities Authority",
"Pittsburgh Water&Sewer Authority",
"PNM",
"Portfolio Manager",
"Portland General Home/Small Business",
"Portland General Medium/Large Business",
"Portland Water",
"Portland Water Bureau",
"Potomac Edison",
"Power Dash",
"PPL Electric Utilities",
"Prescott",
"Providence Water Commercial",
"Providence Water With Username",
"Provo City Utilities",
"Pse MyData",
"PSEG",
"PSEG Long Island",
"PseMyDataManager",
"PSNC Energy",
"PSNH / Eversource",
"Public Service Company of Oklahoma",
"Puerto Rico",
"Puget Sound Energy",
"Quartz Hill",
"Rancho California",
"Randolph Electric",
"Rappahannock Electric Cooperative",
"Real Page",
"RealPage",
"Recology Golden Gate",
"Recology Sunset Scavenger",
"Regional Municipality of Durham",
"Regional Water Authority",
"Reliant Energy",
"Republic Services",
"Rhode Island Energy",
"Rialto Water Services",
"Richmond MyCheckFree",
"Riverside Public Utilities",
"Riviera Utilities",
"Rochester Gas & Electric",
"Rochester Public Utilities",
"Rockwood",
"Rocky Mountain Power",
"Rosenberg",
"Sacramento County",
"Sacramento Municipal Utility District",
"Sacramento Suburban",
"Saint John Energy",
"Salem",
"Salem MA",
"Saline",
"Salt Lake City Public Utilities",
"Salt River Project",
"Sammamish Plateau",
"San Antonio Water System",
"San Diego",
"San Diego Gas and Electric",
"San Francisco Public Utilities Commission",
"San Francisco Public Utilities Commission Daily",
"Sandy Suburban Improvement XpressBillPay",
"Santa Clarita Water Division",
"Santa Fe Irrigation District",
"Santa Margarita",
"Santa Rosa",
"Santee Cooper Electric",
"Sask Energy",
"Saskatoon",
"SaskPower",
"Sawnee EMC",
"SCANA Energy",
"SCV Water",
"SCWA",
"SD1",
"Searcy Water Utilities",
"Seattle City Light",
"Seattle Public Utilities",
"Semco Energy",
"Seminole County Water & Sewer",
"Sevier County Electric System",
"Shakopee Public Utilities",
"Shelby Township Utility Services",
"Silicon Valley",
"Silver Lake Water & Sewer District",
"Silverdale Water Company",
"Sioux Falls Utilities",
"Smartest Energy Ltd",
"SmartMeter Texas",
"Snohomish County PUD",
"Socal Gas Daily Data",
"Solar City",
"Solar Edge",
"Solaros",
"Solren",
"Somerville",
"Soos Creek Water and Sewer",
"Soquel Creek",
"SourceGas",
"South Central Power Co.",
"South County Water System",
"South Jersey Gas",
"South Maryland Electric Coop",
"South River Electric",
"Southern California Edison",
"Southern California Gas",
"Southern California Gas Business",
"Southern Connecticut Gas",
"Southwest Gas",
"Southwest Gas Corporation",
"Southwestern Electric Power",
"Spanaway",
"Spire Energy",
"Sprague",
"Springfield Utility Board",
"Springfield Water & Sewer",
"St. Helena",
"St. Louis Water",
"Stadtwerke Bochum GmbH",
"Stadtwerke Dusseldorf",
"Stadtwerke Zeitz",
"Startex Power",
"Startex-Jackson-Wellford-Duncan Water District",
"Sturgeon Bay",
"Suburban Propane",
"Suburban Water Systems",
"Suez Water",
"Suffolk County Water Authority",
"Summer Energy",
"Summit Water & Supply Co",
"Sun Power",
"Sunny Portal Public",
"Sunrise Water Authority",
"Superior Plus Energy Services",
"Swansea Sewer Dept.",
"SWB Energie und Wasser",
"SWB of New Orleans",
"Sweetwater Authority",
"Syder Comercializadora Verde",
"Sydney Water",
"Symmetry Energy Solutions",
"Tacoma Public Utilities",
"Tallahatchie",
"Tampa Electric Company",
"Taunton MA",
"Taylorsville-Bennion Improvement District XpressBillPay",
"Templeton",
"Tennessee Valley Electric Cooperative",
"Texas Gas Service",
"The Illuminating Company",
"The Metropolitan District",
"Third Taxing District",
"Tidewater Utilities Inc",
"Tigo",
"Toho Water Authority",
"Toledo Edison",
"Toronto Hydro Electric System",
"Toronto Water & Solid Waste Management Services",
"Total Gas & Power",
"Town of Addison",
"Town of Blacksburg",
"Town of Blackstone",
"Town of Cary",
"Town of Chelmsford",
"Town of Duxbury",
"Town of East Gwillimbury",
"Town of Easton",
"Town of Flower Mound",
"Town of Franklin",
"Town of Gilbert",
"Town of Hanover",
"Town of Hartford",
"Town of LaPlata",
"Town of Manchester",
"Town of Marshfield",
"Town of Mooresville NC",
"Town of North Andover",
"Town of Plainfield",
"Town of Queen Creek",
"Town of Watertown",
"Town of Weymouth",
"Township of Langley",
"Township of Winslow",
"TransAlta Corporation",
"Travis County Water Control & Improvement District 17, Texas",
"Trico Electric Cooperative",
"Truckee",
"Tualatin Valley",
"Tucson Electric Power",
"Tucson Water",
"TXU Energy",
"UGI Central Penn Gas",
"UGI Gas",
"UGI Penn Natural Gas",
"UniSource Energy Services",
"United Illuminating",
"United Power",
"Unitil",
"Universal Waste System",
"USVI",
"Utilities Kingston",
"Vacaville",
"Valencia Water Co.",
"Vallecitos",
"Valley County Water District",
"Valley Energy",
"Valparaiso City Utilities",
"Vectren",
"Veolia",
"Verdigris Valley Electric Cooperative",
"Vermont Electric Coop",
"Vermont Gas",
"Village of Buffalo Grove, Illinois",
"Village of Glen Ellyn",
"Village of Glenview",
"Village of Grayslake",
"Village of Montgomery",
"Village of Niles",
"Village of Oak Lawn",
"Village of Watkins Glen",
"Virginia Natural Gas",
"Vista Irrigation District",
"Wagoner",
"Walnut Valley Water District",
"Walton EMC",
"Warrior River Water Authority",
"Wasatch Front Waste & Recycling Dist. XpressBillPay",
"Washington St. Tammany",
"Washington Suburban Sanitary Commission",
"Waste Connections Inc.",
"Waste Management",
"Water Plus",
"Watercare Services Limited",
"Waterloo North Hydro",
"WaterOne",
"WE Energies",
"We Energies Business",
"WE Energies Business",
"We Energies Daily",
"West Des Moines Water Works",
"West Harris County MUD #21",
"West Harris County Municipal Utility District No.1, Texas",
"West Penn Power",
"West Sacramento",
"West Valley Water District",
"Westar Energy",
"Western Massachussetts Electric / Eversource",
"Western Municipal Water District",
"Westfield Gas & Electric",
"White City Water Improvement Dist XpressBillPay",
"Wichita Water",
"Wilsonville",
"Wilsonville Limited",
"Winslow",
"Wisconsin Public Service",
"Withlacoochee River Electric",
"Xcel Energy",
"Xpress South Valley Sewer District",
"Yampa Valley Electric Association",
"Yankee Gas / Eversource",
"Yorba Linda",
"York County Natural Gas",
"York County Water & Sewer",
"York Water Company",
"Youngstown",
"Zelienople Borough"
    ]
    for p in providers:
        c.execute("INSERT INTO directory (city, provider) VALUES (?, ?)", ('Harrisonburg', p))
    conn.commit()

# --- Generate random data for 100 customers if DB is empty ---
c.execute("SELECT COUNT(*) FROM customers")
if c.fetchone()[0] == 0:
    for _ in range(100):
        name = fake.name()
        email = fake.email()
        address = fake.street_address()
        city = fake.city()
        state = fake.state()
        zip_code = fake.zipcode()
        
        c.execute("INSERT INTO customers (name, email, address, city, state, zip) VALUES (?, ?, ?, ?, ?, ?)",
                  (name, email, address, city, state, zip_code))
        customer_id = c.lastrowid

        # Add utility accounts (electric, gas, water)
        for service in ["electric", "gas", "water"]:
            provider = random.choice(["UtilityCo", "EnergyCorp", "AquaFlow", "PowerGrid"])
            account_number = str(random.randint(1000000, 9999999))
            c.execute("INSERT INTO utility_accounts (customer_id, provider, service_type, account_number) VALUES (?, ?, ?, ?)",
                      (customer_id, provider, service, account_number))
            account_id = c.lastrowid

            # Add bills (last 6 months)
            for i in range(6):
                billing_period = datetime.now() - timedelta(days=30 * (i+1))
                amount_due = round(random.uniform(40, 400), 2)
                due_date = billing_period + timedelta(days=30)
                status = random.choice(["pending", "paid"])
                invoice = {"meter": random.randint(1000, 9999), "usage": random.randint(100, 2000)}
                c.execute("INSERT INTO bills (account_id, billing_period, amount_due, due_date, status, provider_invoice) VALUES (?, ?, ?, ?, ?, ?)",
                          (account_id, billing_period.date(), amount_due, due_date.date(), status, json.dumps(invoice)))
                bill_id = c.lastrowid

                # Payments if paid
                if status == "paid":
                    payment_date = due_date - timedelta(days=random.randint(0, 15))
                    method = random.choice(["Stripe", "Plaid", "ACH", "Credit Card"])
                    c.execute("INSERT INTO payments (bill_id, amount, payment_date, method, status) VALUES (?, ?, ?, ?, ?)",
                              (bill_id, amount_due, payment_date, method, "success"))

    conn.commit()

# --- Streamlit UI ---
st.title("Utility Billing Management - Randomized Demo Data with Directory")

st.sidebar.header("Navigation")
menu = ["Dashboard", "Customers", "Utility Accounts", "Bills", "Payments", "Directory", "Export", "Backup"]
choice = st.sidebar.radio("Go to", menu)

# Helper to show SQL query as table
def show_table(query):
    df = pd.read_sql_query(query, conn)
    st.dataframe(df)
    return df

# Dashboard Summary
if choice == "Dashboard":
    st.subheader("📊 Quick Overview")
    total_customers = pd.read_sql_query("SELECT COUNT(*) as cnt FROM customers", conn)["cnt"][0]
    total_accounts = pd.read_sql_query("SELECT COUNT(*) as cnt FROM utility_accounts", conn)["cnt"][0]
    total_bills = pd.read_sql_query("SELECT COUNT(*) as cnt FROM bills", conn)["cnt"][0]
    total_payments = pd.read_sql_query("SELECT COUNT(*) as cnt FROM payments", conn)["cnt"][0]
    total_directory = pd.read_sql_query("SELECT COUNT(*) as cnt FROM directory", conn)["cnt"][0]

    st.metric("Total Customers", total_customers)
    st.metric("Utility Accounts", total_accounts)
    st.metric("Bills Recorded", total_bills)
    st.metric("Payments Made", total_payments)
    st.metric("Directory Entries", total_directory)

elif choice == "Customers":
    st.subheader("👥 Customers")
    df = show_table("SELECT * FROM customers")
    st.write("Add / Edit / Delete functionality is available in the code for extension.")

elif choice == "Utility Accounts":
    st.subheader("🔌 Utility Accounts")
    df = show_table("SELECT * FROM utility_accounts")

elif choice == "Bills":
    st.subheader("🧾 Bills")
    df = show_table("SELECT * FROM bills")

elif choice == "Payments":
    st.subheader("💳 Payments")
    df = show_table("SELECT * FROM payments")

elif choice == "Directory":
    st.subheader("📚 Harrisonburg Utility/Provider Directory")
    q = st.text_input("Search providers (type name or partial)", "")
    filter_city = st.selectbox("City", ["Harrisonburg"], index=0)
    if q:
        df = pd.read_sql_query("SELECT * FROM directory WHERE city = ? AND provider LIKE ?", conn, params=(filter_city, f"%{q}%"))
    else:
        df = pd.read_sql_query("SELECT * FROM directory WHERE city = ?", conn, params=(filter_city,))
    st.dataframe(df)
    st.write(f"{len(df)} providers shown")

elif choice == "Export":
    st.subheader("📤 Export Database Tables")
    for table in ["customers", "utility_accounts", "bills", "payments", "directory"]:
        df = pd.read_sql_query(f"SELECT * FROM {table}", conn)
        st.download_button(
            label=f"Download {table}.csv",
            data=df.to_csv(index=False).encode("utf-8"),
            file_name=f"{table}.csv",
            mime="text/csv"
        )

elif choice == "Backup":
    st.subheader("💾 Backup / Download SQLite DB")
    # Create in-memory zip of sqlite file
    conn.backup(sqlite3.connect('backup_temp.db'))
    with open('backup_temp.db', 'rb') as f:
        db_bytes = f.read()
    zbuf = io.BytesIO()
    with zipfile.ZipFile(zbuf, 'w', zipfile.ZIP_DEFLATED) as zf:
        zf.writestr('utilities.db', db_bytes)
    zbuf.seek(0)
    st.download_button("Download DB Backup (zip)", zbuf, file_name='utilities_backup.zip')

# Close connection when Streamlit session ends (Streamlit will keep process alive otherwise)
# conn.close()

